# nodes:
# - input.visual:
#     source: 1
# - custom_nodes.model.sp_ppe_1_yolox:
#     exp_path: "./exps/custom/sp_ppe_1/sp_ppe_1.py"
#     ckpt_file: "./weights/sp_ppe_1/best_ckpt_s_dev.pth"
#     confthre: 0.7
#     nmsthre: 0.5
# - custom_nodes.draw.sp_ppe_1_bbox_cond_color:
#     show_labels: True
# - custom_nodes.draw.sp_ppe_1_score_cond_color
# - output.screen
# # - output.csv_writer:
# #     stats_to_track: ["filename", "bboxes", "bbox_labels"]
# #     file_path: ./pkd_outputs/all_annotations.csv
# #     logging_interval: 0
# # - output.media_writer:
# #     output_dir: ./pkd_outputs


nodes:
- input.visual:
    source: 0
- custom_nodes.model.sp_ppe_1_yolox:
    exp_path: "./exps/custom/sp_ppe_1/sp_ppe_1.py"
    ckpt_file: "./weights/sp_ppe_1/best_ckpt_s_dev.pth"
    confthre: 0.7
    nmsthre: 0.5
- custom_nodes.draw.sp_ppe_1_bbox_cond_color:
    show_labels: True
- custom_nodes.draw.sp_ppe_1_score_cond_color
- dabble.tracking
- custom_nodes.output.sp_ppe_1_vid2img_writer:
    output_dir: ./pkd_outputs/output_images
    num_img_to_store: 200
- custom_nodes.output.sp_ppe_1_smart_notification
- output.screen