nodes:
- input.visual:
    source: 1
    # source: ./datasets/pascal_voc/images/all_ppe--1-_jpg.rf.90bf10c92a532b472017aae1ff221085.jpg
- custom_nodes.model.ppe_detection
- draw.bbox:
    show_labels: true
- output.screen
- output.media_writer