input: ["img"]
output: ["bboxes", "bbox_labels", "bbox_scores"]

exp_path: "./exps/custom/sp_ppe_1/sp_ppe_1.py"
ckpt_file: "./YOLOX_outputs/sp_ppe_1/best_ckpt.pth"

voc_classes: {
    0: "no ppe",
    1: "all ppe",   # this class is linked to draw.bbox and draw.score custom nodes
    2: "helmet",
    3: "mask",
    4: "vest",
    5: "mask + vest",
    6: "helmet + mask",
    7: "helmet + vest",
}

device: "gpu"
fp16: false
confthre: 0.7
nmsthre: 0.5
